---
title: "vis_descr"
output: html_document
date: "2025-11-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)

library(flextable)
library(tidyverse)
library(readxl)
library(forcats)
```

```{r}
hypertension <- read_xlsx("data/originals/DominicanHTN_add_sign.xlsx")
```

```{r}
glimpse(hypertension)
```


```{r}
ggplot(hypertension)+
  geom_bar(aes(x=Gender))
```


```{r}
hypertension %>% count(Gender)
```
```{r}
hypertension %>% count(Village) %>% arrange(n)
```

```{r}
median_age <- hypertension %>% group_by(Gender) %>% summarise(median_age=median(Age))
labels <- hypertension %>%
  group_by(Village) %>%
  summarise(total = n()) %>%
  mutate(Village_label = paste0(Village, " (", total, ")"))
```

```{r, fig.width=11, fig.height=4}
ggplot(hypertension) +
  geom_bar(aes(x = fct_infreq(Village), fill = Gender), alpha=0.8) + gender_fill +
  labs(x="", y="Число жителей",title="Число жителей и гендерный состав населенных пунктов")+axis_theme
```

```{r, fig.width=12, fig.height=4}
village_stats <- hypertension %>%
  group_by(Village) %>%
  summarise(
    total = n(),
    pct_female = mean(Gender == "Female") * 100
  )
ggplot(village_stats, aes(x = fct_reorder(Village, total, .desc = T), y = total, fill = pct_female)) +
  geom_col() +
  scale_fill_gradient(low = "#1b909a", high = "#eb4729", name = "% женщин") +
  labs(x = "", y = "Число жителей", title="Число жителей и гендерный состав населенных пунктов") + axis_theme
```
```{r, fig.width=12, fig.height=4}
village_stats <- hypertension %>%
  group_by(Village) %>%
  summarise(
    total = n(),
    pct_female = mean(Gender == "Female") * 100
  )
ggplot(village_stats, aes(x = fct_reorder(Village, total, .desc = T), y = total, fill = pct_female)) +
  geom_col() +
  scale_fill_gradient(low = "#9BCD9B", high = "darkolivegreen", name = "% женщин") +
  labs(x = "", y = "Число жителей", title="Число жителей и гендерный состав населенных пунктов") + axis_theme
```


```{r}
ggplot(hypertension)+
  geom_histogram(aes(x=Age), bins=30)+
  facet_grid(.~Gender)

```

```{r}
ggplot(hypertension, aes(x = Age, fill = Gender)) + 
  geom_density(alpha = 0.5)
```


```{r}
no_legend <- theme(
    legend.position= "none"
  )
no_y <- labs(
  y = ""
)

gender_fill <- scale_fill_manual(name= "Пол",
                   labels = c("Female" = "Женский", "Male" = "Мужской"),
                   values=c(
                    "Male" = "#1b909a",
                    "Female" = "#eb4729")
)
gender_col <- scale_colour_manual(name= "Пол",
                   labels = c("Female" = "Женский", "Male" = "Мужской"),
                   values=c(
                    "Male" = "#1b909a",
                    "Female" = "#eb4729")
)
theme_set(theme_bw())
axis_theme <- theme(
    plot.title = element_text(size=20, hjust=0.5),
    plot.subtitle = element_text(size=14, hjust=0.5),
    axis.title = element_text(size=16),
    axis.text.y = element_text(size=12),
    axis.text.x = element_text(size=12),
    legend.title = element_text(size = 16),
    legend.text = element_text(size = 14),
    )
```

```{r, fig.height=7}
p1 <- ggplot(hypertension, aes(x = SBP, fill = Gender)) + 
  geom_density(alpha = 0.5) + no_legend + labs(x = "ДАД") + scale_x_continuous(breaks = seq(80, 350, 20))
p2 <- ggplot(hypertension, aes(x = DBP, fill = Gender)) + 
  geom_density(alpha = 0.5) + no_legend + labs(x = "САД") + scale_x_continuous(breaks = seq(20, 350, 20))
p3 <- ggplot(hypertension, aes(x = Age, fill = Gender)) + 
  geom_density(alpha = 0.5) + labs(x = "Возраст") + scale_x_continuous(breaks=seq(0, 100, 10))

# +   geom_vline(data = median_age, aes(xintercept = median_age, color = Gender), size = 1.5)
library(patchwork)
(p2 + p1) / p3 + plot_annotation(title = "Распределение количественных признаков у мужчин и женщин") + plot_layout(guides = "collect") & no_y & gender_fill & axis_theme
```

```{r, fig.width=10}
p1 <- ggplot(hypertension, aes(x=Age, y=SBP, color=Gender))+
  geom_point() + labs(x = "Возраст", y="САД") + scale_y_continuous(breaks = seq(20, 350, 20))
p2 <- ggplot(hypertension, aes(x=Age, y=DBP, color=Gender))+
  geom_point() + labs(x = "Возраст", y="ДАД") + scale_y_continuous(breaks = seq(20, 350, 20))
p1 + p2 + plot_layout(guides = "collect") + plot_annotation(title = "Зависимость САД и ДАД от возраста для мужчин и женщин") & gender_col & axis_theme & theme(legend.position = "bottom") 
```

```{r}
ggplot(hypertension)+
  geom_histogram(aes(x=SBP), bins=25)
```


```{r}
ggplot(hypertension)+
  geom_histogram(aes(x=DBP), bins=25)
```


```{r}
library(ggpubr)
ggplot(hypertension, aes(x=Age, y=SBP, color=Gender))+
  geom_point()+
  geom_smooth(method=lm, show.legend = TRUE, se=FALSE)+
  stat_regline_equation()+
  stat_cor(label.y = c(200, 190))
```


```{r}
ggplot(hypertension, aes(x=Age, y=DBP, color=Gender))+
  geom_point()+
  geom_smooth(method=lm, show.legend = TRUE, se=FALSE)+
  stat_regline_equation()+
  stat_cor(label.y = c(125, 115))
```


```{r}
ggplot(hypertension, aes(x=SBP, y=DBP, colour=Gender))+
  geom_point()+
    geom_smooth(method=lm, show.legend = TRUE, se=FALSE)+
  stat_regline_equation()+
  stat_cor(label.y = c(125, 115))
```


```{r}
ggplot(hypertension)+
  geom_point(aes(x=SBP, y=DBP, colour=Age))
```


```{r}
ggplot(hypertension)+
  geom_point(aes(x=SBP, y=DBP, colour=Village))
```


```{r}
ggplot(hypertension)+
  geom_point(aes(x=Age, y=SBP, colour=Village))
```

```{r}
library(ggridges)
ggplot(hypertension)+
  geom_density_ridges(aes(x=SBP, y=Village, fill=Village))
```

```{r}
ggplot(hypertension)+
  geom_density_ridges(aes(x=DBP, y=Village, fill=Village))
```


```{r}
ggplot(hypertension)+
  geom_density_ridges(aes(x=Age, y=Village, fill=Village))
```


```{r}
f_hypertension <- hypertension %>% filter(Gender == "Female")
m_hypertension <- hypertension %>% filter(Gender == "Male")
```


```{r}
ggplot(hypertension)+
  geom_density_ridges(aes(x=Age, y=Village, fill=Village)) +
  facet_grid(Gender~.)
```


```{r}
ggplot(hypertension)+
  geom_density_ridges(aes(x=SBP, y=Village, fill=Village)) +
  facet_grid(Gender~.)
```


```{r}
f_hypertension %>% filter(Village=="Batey Verde") %>% arrange(SBP)
```


```{r}
m <- lm(SBP ~ Gender * Age, data = hypertension)
summary(m)
```
```{r}
m <- lm(SBP ~ Village, data = hypertension)
summary(m)
```


